// crops.ts
export const crops = [
  {
    id: 1,
    name: "Rice",
    image: "https://images.unsplash.com/photo-1614091066096-4c6521fbea3f?auto=format&fit=crop&q=60&w=600&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjh8fHJpY2V8ZW58MHx8MHx8fDA%3D",
    desc: "Rice, a primary dietary component for over half the global populace, is a versatile and indispensable grain enjoyed across diverse cuisines. Cultivated in varied strains, such as long-grain, medium-grain, and short-grain, rice serves as a substantial source of energy and nutrients. Known for its adaptability, it complements dishes ranging from savory to sweet. Beyond its culinary significance, rice plays a vital role in cultural rituals and traditions worldwide, symbolizing prosperity and sustenance. Rich in carbohydrates and gluten-free, rice continues to be a crucial element in fostering food security and supporting agricultural economies.",
  },
  {
    id: 2,
    name: "Maize",
    image: "https://images.unsplash.com/photo-1634666328718-ad6af3112aff?auto=format&fit=crop&q=80&w=1974&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Maize, also known as corn, is a cereal grain that is a staple in many diets worldwide. It is used for human consumption, livestock feed, and various industrial products.",
  },
  {
    id: 3,
    name: "Chickpea",
    image: "https://plus.unsplash.com/premium_photo-1675237625824-40a9c6400ad8?auto=format&fit=crop&q=80&w=1974&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Chickpea, also known as garbanzo bean, is a nutritious legume high in protein and fiber. It is a key ingredient in many dishes, including hummus and various soups.",
  },
  {
    id: 4,
    name: "Kidneybeans",
    image: "https://res.cloudinary.com/dya8zifir/image/upload/v1698764333/agroApiProfile/kidney-beans_u9imzs.jpg",
    desc: "Kidney beans are a rich source of protein, fiber, and various vitamins and minerals. They are commonly used in salads, soups, and various cuisines around the world.",
  },
  {
    id: 5,
    name: "Pigeonpeas",
    image: "https://chefsmandala.com/wp-content/uploads/2018/04/Pigeon-Pea.jpg",
    desc: "Pigeon peas are a nutritious legume that is often used in soups, stews, and curries. They are a good source of protein, fiber, and essential nutrients.",
  },
  {
    id: 6,
    name: "Mothbeans",
    image: "https://ooofarms.com/cdn/shop/products/MothBean1_whole.jpg?v=1672251298&width=3840",
    desc: "Moth beans, also known as matki, are a type of legume that is rich in protein and nutrients. They are commonly used in Indian cuisine in various dishes.",
  },
  {
    id: 7,
    name: "Blackgram",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Black_gram.jpg/1200px-Black_gram.jpg",
    desc: "Black gram, also known as urad dal, is a highly nutritious pulse. It is a common ingredient in Indian cuisine and is used to make dishes like dal makhani.",
  },
  {
    id: 8,
    name: "Lentil",
    image: "https://images.unsplash.com/photo-1601941187195-182cd1e7fc5c?auto=format&fit=crop&q=60&w=600&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bGVudGlsfGVufDB8fDB8fHww",
    desc: "Lentils are a nutritious legume rich in protein, fiber, and various essential nutrients. They are used in a variety of dishes, including soups, stews, and salads.",
  },
  {
    id: 9,
    name: "Pomegranate",
    image: "https://images.unsplash.com/photo-1580157508103-2a4e9fe8ed29?auto=format&fit=crop&q=60&w=600&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cG9tZWdyYW5hdGV8ZW58MHx8MHx8fDA%3D",
    desc: "Pomegranate is a delicious and nutrient-rich fruit. It is known for its juicy seeds and is consumed fresh, juiced, or used as a flavorful addition to various dishes.",
  },
  {
    id: 10,
    name: "Banana",
    image: "https://images.unsplash.com/photo-1603833665858-e61d17a86224?auto=format&fit=crop&q=60&w=600&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8QmFuYW5hfGVufDB8fDB8fHww",
    desc: "Bananas are a popular and nutritious fruit. They are rich in potassium, vitamins, and antioxidants. Bananas are consumed fresh and are a versatile ingredient in various recipes.",
  },
  {
    id: 11,
    name: "Mango",
    image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&q=80&w=1935&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Mango is a tropical fruit known for its sweet and flavorful taste. It is rich in vitamins, minerals, and antioxidants. Mangoes are enjoyed fresh, juiced, or in various dishes.",
  },
  {
    id: 12,
    name: "Grapes",
    image: "https://images.unsplash.com/photo-1539519532614-723937382b86?auto=format&fit=crop&q=60&w=600&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8R3JhcGVzfGVufDB8fDB8fHww",
    desc: "Grapes are delicious and nutritious fruits that come in various colors. They are enjoyed fresh, dried as raisins, or used to make juices, wines, and various culinary dishes.",
  },
  {
    id: 13,
    name: "Watermelon",
    image: "https://images.unsplash.com/photo-1628160154851-ea8b3d79ef0a?auto=format&fit=crop&q=60&w=600&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjB8fFdhdGVybWVsb258ZW58MHx8MHx8fDA%3D",
    desc: "Watermelon is a refreshing and hydrating fruit with sweet, juicy flesh. It is a popular summer fruit enjoyed fresh, in salads, and as a thirst-quenching snack.",
  },
  {
    id: 14,
    name: "Muskmelon",
    image: "https://images.unsplash.com/photo-1646992122113-bd1f335187ac?auto=format&fit=crop&q=60&w=600&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bXVza21lbG9ufGVufDB8fDB8fHww",
    desc: "Muskmelon, also known as cantaloupe, is a sweet and aromatic fruit. It is rich in vitamins and minerals, making it a healthy and delicious addition to fruit salads and desserts.",
  },
  {
    id: 15,
    name: "Apple",
    image: "https://images.unsplash.com/photo-1589217157232-464b505b197f?auto=format&fit=crop&q=80&w=1974&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Apple is a crisp and flavorful fruit with various varieties. It is rich in fiber, vitamins, and antioxidants. Apples are enjoyed fresh, in juices, and as a versatile ingredient in cooking.",
  },
  {
    id: 16,
    name: "Orange",
    image: "https://images.unsplash.com/photo-1580052614034-c55d20bfee3b?auto=format&fit=crop&q=60&w=600&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8T3JhbmdlfGVufDB8fDB8fHww",
    desc: "Orange is a citrus fruit known for its sweet and tangy flavor. It is a rich source of vitamin C and is enjoyed fresh, juiced, or used in various culinary applications.",
  },
  {
    id: 17,
    name: "Papaya",
    image: "https://images.unsplash.com/photo-1623492229905-ebc1202e8904?auto=format&fit=crop&q=80&w=2080&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Papaya is a tropical fruit with sweet and vibrant orange flesh. It is rich in vitamins, enzymes, and antioxidants. Papaya is enjoyed fresh and is used in smoothies and salads.",
  },
  {
    id: 18,
    name: "Coconut",
    image: "https://images.unsplash.com/photo-1537191072641-5e19cc173c6a?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Coconut is a versatile fruit with sweet, nutty flavor. It provides coconut water, milk, and oil used in various cuisines. Coconuts are also enjoyed fresh or dried as snacks.",
  },
  {
    id: 19,
    name: "Cotton",
    image: "https://images.unsplash.com/photo-1634337781106-4c6a12b820a1?auto=format&fit=crop&q=60&w=600&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fENvdHRvbnxlbnwwfHwwfHx8MA%3D%3D",
    desc: "Cotton is a crucial fiber crop used in textile production. It is cultivated for its soft and fluffy fibers, which are used to make clothing, textiles, and various industrial products.",
  },
  {
    id: 20,
    name: "Jute",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Jute_Cultivation_and_Processing_Bangladesh_%288%29.JPG/1200px-Jute_Cultivation_and_Processing_Bangladesh_%288%29.JPG?20091217072323",
    desc: "Jute is a natural fiber crop used for making burlap, sacks, and other eco-friendly products. It is known for its strength and versatility, making it an important crop in various industries.",
  },
  {
    id: 21,
    name: "Coffee",
    image: "https://images.unsplash.com/photo-1551610290-e153ec567dd8?auto=format&fit=crop&q=80&w=1926&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Coffee is a popular beverage made from roasted coffee beans. It is enjoyed worldwide for its rich flavor and stimulating effects. Coffee beans are cultivated in coffee plantations.",
  },
  {
    id: 22,
    name: "Mungbean",
    image: "https://cdn.wikifarmer.com/wp-content/uploads/2023/07/Mung-Bean-Plant-Information-Uses-Nutritional-Value-and-Health-Venefits.jpg",
    desc: "Mungbean, also known as green gram, is a nutrient-rich legume widely used in various cuisines. It is valued for its high protein content, vitamins, and minerals. Mungbeans are commonly sprouted and used in salads, soups, and curries.",
  },
];
